package epam.jwd.online_training.command;

public enum CommandType {
    LOGIN,
    LOGOUT,
    SIGNUP,
    LOCALE,
    ADDCOURSE,
    ADDTEACHER,
    ADDTASK,
    DELETEUSER,
    EDITCOURSE,
    GETPAGE,
    GETTAKENCOURSES,
    JOINCOURSE,
    RECOVERPASSWORD,
    SENDANSWER,
    SENDREVIEW,
    TAKEALLCOURSES,
    TAKEALLTEACHERS,
    TAKEAVAILABLECOURSES,
    TAKECOURSERELATEDTASKS,
    TAKERECEIVEDTASKS,
    TAKEREVIEWSBYTASKID,
    TAKETEACHERRELATEDCOURSES;
}
